# This workflow will build and deploy a static web app to Azure Static Web Apps on push to a branch or pull request event

name: Azure Static Web Apps CI/CD

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  NODE_VERSION: 14.x

# Jobs in this workflow
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build the app
        run: npm run build
      - name: Generate Azure Static Web Apps configuration file
        run: npx @azure/static-web-apps-cli swa-config --output .github/staticwebapp.config.json --app-location ./build
      - name: Deploy the app to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # App configuration
          app_location: "/"
          output_location: "/build"
          # GitHub Action token
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
